attributes:
  metadata:
    restrictions:
      - condition: "settings:lma_infrastructure_alerting == null or settings:lma_infrastructure_alerting.metadata.enabled == false "
        action: "hide"
        message: "This plugin requires lma_infrasturuture_alerting plugin"
        strict: false

  sfdc_client_id:
    value: ''
    label: 'SalesForce Client ID. Should be provided by SFDC administartors, looks like long random string. ( Example of SFDC Client ID: 3MVG ...  )'
    weight: 60
    type: "text"
    regex: &not_empty_parameter
      source: '\S'
      error: "Invalid value"

  sfdc_client_secret:
    value: ''
    label: 'SalesForce Client Secret. Should be provided by SFDC administartors, looks like string contains only digits. (Example of SFDC Client Secret: 5523245751213467826)'
    weight: 65
    type: "text"
    regex: *not_empty_parameter


  sfdc_auth_url:
    value: ''
    label: 'SalesForce auth url, looks like https://some-domain.my.salesforce.com'
    weight: 70
    type: "text"
    regex: *not_empty_parameter


  sfdc_username:
    value: ''
    label: 'SalesForce UserName'
    weight: 75
    type: "text"
    regex: *not_empty_parameter


  sfdc_password:
    value: ''
    label: 'SalesForce password'
    weight: 80
    type: "password"
    regex: *not_empty_parameter


  environment:
    value: ''
    label: 'Cloud ID, sould be provided by SFDC administrators. Example: a3X990000009QP8MEA'
    weight: 85
    type: "text"
    regex: *not_empty_parameter


  sfdc_organization_id:
    value: ''
    label: 'SFDC Organization ID should be provided by SFDC administartors. Example: 00F370000006c1e'
    weight: 90
    type: "text"
    regex: *not_empty_parameter



  host_regexp:
    value: 'host=[a-z,A-Z,\-,0-9,\.]*'
    label: 'Regular expression to find affected host in nagios service output'
    weight: 90
    type: "text"
    regex: *not_empty_parameter


#  log_file:
#    value: '/var/log/nagios_to_sfdc.log'
#    label: 'log file name'
#    weight: 90
#    type: "text"
#    regex: *not_empty_parameter



  max_time:
    value: '3600'
    label: 'Message TTL in queue in seconds.'
    weight: 90
    type: "text"
    regex: *not_empty_parameter




  max_attempts:
    value: '100'
    label: 'Max number of attempts to create object in SFDC'
    weight: 90
    type: "text"
    regex: *not_empty_parameter

  sleep_time:
    value: '5'
    label: 'Timeout between retrys'
    weight: 90
    type: "text"
    regex: *not_empty_parameter



